config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tickets#index'

  namespace :api do
    namespace :v1 do
      resource :ticket, only: :create
    end
  end

  resources :tickets, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/excavator.rb
# frozen_string_literal: true

class Excavator < ApplicationRecord
end

app/models/ticket.rb
# frozen_string_literal: true

class Ticket < ApplicationRecord
  has_one :excavator

  def self.coord_to_a(polygons)
    polygons.scan(/-\d+\.\d+\s*\d+\.\d+\s*[^,)]/)
  end
end

app/controllers/api/v1/api_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ApiController < ActionController::API
      before_action :set_default_format

      private

      def set_default_format
        request.format = :json
      end
    end
  end
end

app/controllers/api/v1/tickets_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class TicketsController < ApiController
      def create
        request.format = :json
        @ticket = Ticket.new(ticket_params)

        if @ticket.save && @ticket.create_excavator(excavator_params)
          render json: { message: 'Successfully saved' }, status: :ok
        else
          render json: { message_s: @ticket.errors.full_messages }, status: :bad_request
        end
      end

      private

      def ticket_params
        params.permit(:request_number, :sequence_number, :request_type).tap do |whitelisted|
          whitelisted[:response_due_date_time] = params[:date_times][:response_due_date_time]
          whitelisted[:primary_service_area_sa_code] = params[:service_area][:primary_service_area_code][:sa_code]
          whitelisted[:additional_service_area_sa_code] = params[:service_area][:additional_service_area_codes][:sa_code]
          whitelisted[:well_known_text] = Ticket.coord_to_a(params[:excavation_info][:digsite_info][:well_known_text])
        end
      end

      def excavator_params
        params.permit.tap do |whitelisted|
          whitelisted[:address] = {
            address: params[:excavator][:address],
            city: params[:excavator][:city],
            state: params[:excavator][:state],
            zip: params[:excavator][:zip]
          }
          whitelisted[:company_name] = params[:excavator][:company_name]
          whitelisted[:crew_onsite] = params[:excavator][:crew_onsite]
        end
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/tickets_controller.rb
# frozen_string_literal: true

class TicketsController < ApplicationController # :nodoc:
  def index
    @tickets = Ticket.all
  end

  def show
    @ticket = Ticket.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
# frozen_string_literal: true

module TicketsHelper
  def normalize_ticket(ticket)
    ticket.each_key do |key|
      ticket[key] = ticket[key].join(', ')        if ticket[key].kind_of?(Array)
      ticket[key] = ticket[key].strftime('%v %T') if ticket[key].kind_of?(ActiveSupport::TimeWithZone)
      ticket.delete(key)                          if ticket_fields.include?(key)
    end
  end

  # excavator address
  def normalize_address(address)
    address.delete('address')
    address
  end

  private

  def ticket_fields
    %w[id well_known_text created_at updated_at]
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Ticket and Excavator
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      %header
        %h3
          =link_to('tickets excavators', root_path)
      %main
        =yield
      %footer.text-center
        Rails 5.2.2

app/views/tickets/_excavator.html.haml
.row
  .col-4
    company name:&nbsp
  .col-8
    =excavator.company_name
  .col-4
    address:&nbsp
  .col-8
    =excavator.address['address']
  -normalize_address(excavator.address).values.each do |value|
    .col-8.offset-4
      =value
  .col-4
    crew on site:&nbsp
  .col-8
    =excavator.crew_onsite

app/views/tickets/_ticket.html.haml
-normalize_ticket(ticket).each do |key, value|
  .row
    .col-6
      =key.humanize + ':'
    .col-6.d-flex.align-items-center
      =value

app/views/tickets/index.html.haml
.row
  .col-4.offset-4
    -if @tickets.count.zero?
      empty
    -else
      -@tickets.each do |ticket|
        =link_to(ticket_path(ticket), class: 'ticket') do
          =ticket.request_number
          .ticket-icon
            =image_tag(asset_path('ticket.png', alt: 'ticket icon'))

app/views/tickets/show.html.haml
#info
  .row
    #ticket.col-5.offset-1
      %h3.mb-0.border-bottom.border-secondary
        Ticket
      =render 'ticket', ticket: @ticket.as_json
    #excavator.col-5
      %h3.mb-0.border-bottom.border-secondary
        Excavator
      =render 'excavator', excavator: @ticket.excavator
#google-maps
  .row
    .col-2.offset-1#tabs

    .col-8#map